### ISSUE TITLE
The order can be sent without confirmation of Terms. (prepayment)

### ISSUE THREAD

**Issue by garbast** [CommerceTeam/commerce#81]
Thanks to Matthias Krappitz, for finding the bug.

Transfered from forge with Issue Number 30579
[class.tx_commerce_pi3.php.patch.txt](https://github.com/CommerceTeam/commerce/files/135714/class.tx_commerce_pi3.php.patch.txt)

**Comment by garbast** [comment]
Sebastian Fischer -
Please recheck as i cant reproduce it with the current code

**Comment by sir-gawain** [comment]
The issue is in the current code too. The problem is the order of checks in the if-statement.
Prepayment::checkExternalData() always returns true. This true is negated in the first part of the if-statement to false. if(false && X) is always false, and modern interpreters/compilers do not check X at all in this case. The terms check is effectively disabled.
The patch is wrong, btw. It only changes the if from (X && (Y || Z)) to ((X && Y) || Z), and removes the empty()-check. 
Not sure how to fix this, as i do not know, what checkExternalData() is supposed to do. Why is it checked together with the terms? I think, it should have its own test and error message.

**Comment by garbast** [comment]
The patch first and formost is old as heck, so dont expect it to match.

Further more i didn't checked it lately as i'm only working on the EAP branch. If this is a problem please submit a pullrequest after fixing it.
